### ISSUE TITLE
光标向后偏移

### ISSUE THREAD

**Issue by dgeibi** [ghosert/cmd-editor#1050]
Chromium in Archlinux

输入的字符越多，偏移越厉害

轻量编辑器没有这个问题

![screenshot_2015-12-29_15-07-10](https://cloud.githubusercontent.com/assets/2224764/12030731/2a82647a-ae3e-11e5-9ac0-b30425463959.png)

**Comment by ghosert** [comment]
选个等宽字体即可。 发自网易邮箱大师 在2015年12月29日 15:09 ，Xavier Peng写道： Chromium in Archlinux 输入的字符越多，偏移越厉害 轻量编辑器没有这个问题 — Reply to this email directly or view it on GitHub.

**Comment by dgeibi** [comment]
看起来轻量编辑器和高级用的字体一样，就高级编辑器出问题

**Comment by ghosert** [comment]
我知道，还是要用等宽字体。 发自网易邮箱大师 在2015年12月29日 16:30 ，Xavier Peng写道： 看起来轻量编辑器和高级用的字体一样，就高级编辑器出问题 — Reply to this email directly or view it on GitHub.

**Comment by dgeibi** [comment]
fontconfig 设置了 还是那样

**Comment by ghosert** [comment]
浏览器里能设置吗？ 发自网易邮箱大师 在2015年12月29日 16:38 ，Xavier Peng写道： fontconfig 设置了 还是那样 — Reply to this email directly or view it on GitHub.

**Comment by dgeibi** [comment]
设了和没设一样，高级模式光标比低级模式的光标粗

**Comment by ghosert** [comment]
呃，你能装google chrome 吗？你这个发行版和浏览器我都没测过。我只测过 google chrome + ubuntu

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-12-29 16:53 GMT+08:00 Xavier Peng notifications@github.com:

**Comment by dgeibi** [comment]
google chrome 装了也是那样的，另外中文没有偏移现象

**Comment by ghosert** [comment]
firefox 呢？客户端呢？

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

2015-12-29 16:57 GMT+08:00 Xavier Peng notifications@github.com:

**Comment by ghosert** [comment]
要不试试客户端？ https://www.zybuluo.com/cmd

_键盘狂热爱好者神经衰弱，强迫症患者作业部落：http://www.zybuluo.com
http://www.zybuluo.com个人博客：http://ghosertblog.github.com
http://ghosertblog.github.com新浪微博：http://www.weibo.com/ghosert
http://www.weibo.com/ghosert豆瓣社区：http://book.douban.com/people/ghosert
http://book.douban.com/people/ghosert/_

在 2015年12月29日 下午4:59，Zhang Jiawei ghosert@gmail.com写道：

**Comment by dgeibi** [comment]
Firefox 也是那样，嗯，试试

**Comment by dgeibi** [comment]
客户端也那样

**Comment by ghosert** [comment]
那可能发行版的问题，你网上找找办法给你的发行版装个微软雅黑，然后浏览器里选这个微软雅黑，应该就好了。 发自网易邮箱大师 在2015年12月29日 17:13 ，Xavier Peng写道： 客户端也那样 — Reply to this email directly or view it on GitHub.

**Comment by dgeibi** [comment]
编辑区的字体我不会改，我只能改预览区的字体，用的是改 CSS

**Comment by ghosert** [comment]
不是用css改，是要去浏览器的字体设置里改。 发自网易邮箱大师 在2015年12月29日 18:10 ，Xavier Peng写道： 编辑区的字体我不会改，我只能改预览区的自体，用的是改 CSS — Reply to this email directly or view it on GitHub.

**Comment by dgeibi** [comment]
应该是网页默认等宽字体我没装上，我怎么设都不行……告诉我字体名字就行了

**Comment by dgeibi** [comment]
似乎装了 Consolas 就好了

**Comment by dgeibi** [comment]
网站 css 这样

``` css
code,pre{padding:0 3px 2px;font-family:Monaco,Menlo,Consolas,"Courier New",monospace;font-size:12px;color:#333;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}
```

但是系统装了 Monaco、monospace 都失效，只有 Consolas 生效

**Comment by dgeibi** [comment]
我明白了，字体支持太少了，至少在 WenQuanYi Micro Hei 前加 Monaco, monospace 吧

``` css
.wmd-input,.wmd-input:focus,#md-section-helper{width:100%;border:0;padding:0 6px;box-shadow:0 1px 1px rgba(0,0,0,.075) inset;transition:border .2s linear 0s,box-shadow .2s linear 0s;font-size:16px;line-height:27px;resize:none;overflow-x:hidden;font-family:Menlo,"Ubuntu Mono",Consolas,"Courier New",Microsoft Yahei,Hiragino Sans GB,WenQuanYi Micro Hei,sans-serif}
```

**Comment by ghosert** [comment]
其实装个 Microsoft Yahei 或者 WenQuanYi Micro Hei 就好了，我没测过你这个发行版，不知道少了什么字体。你确定 Monaco 在 Archlinux 有，并且是等宽吗？

如果确定我下次加进去。

**Comment by dgeibi** [comment]
Monaco 是 os x 自带的等宽字体，我另外装的。文泉驿微黑也是要另外装的，不过我装了也没用，也许是因为名字没对上吧
2015年12月30日 下午1:37，"Jay Zhang" notifications@github.com写道：

**Comment by ghosert** [comment]
那我也没办法加，一般只加系统自带的等宽字体。Archlinux 就按装 Consolas 来解决吧，既然你试下来可行。

**Comment by dgeibi** [comment]
至少要加个 monospace，monospace 是自带的等宽字体，刚刚打错了，不好意思。
2015年12月30日 下午1:45，"Jay Zhang" notifications@github.com写道：

**Comment by ghosert** [comment]
那你能不能手动回复成不行的时候，然后在CSS里手动加上 MONOSPACE，证明也能解决问题？如果可以我下次加。

**Comment by dgeibi** [comment]
``` css
.wmd-input,.wmd-input:focus,#md-section-helper{width:100%;border:0;padding:0 6px;box-shadow:0 1px 1px rgba(0,0,0,.075) inset;transition:border .2s linear 0s,box-shadow .2s linear 0s;font-size:16px;line-height:27px;resize:none;overflow-x:hidden;font-family:monospace!important}
```

测试通过
