### ISSUE TITLE
要求增加段落缩进功能或者增加自定义或导入css的功能

### ISSUE THREAD

**Issue by iceprosurface** [ghosert/cmd-editor#1216]
自己手动加css也不是不可以，但是最好能一次设定处处生效吧~
so希望增加段落缩进或者增加自定义css的功能。
一般情况下段落都需要缩进2字符吧，或者允许我们自定义一部分样式表吧

``` css
p {
  /*text-indent:2rem;*/
  padding-left:2rem;
}
```
