### ISSUE TITLE
请诸位用户使用本贴提交自己书写的 Cmd 自定义 CSS 方便共享和交流书写样式

### ISSUE THREAD

**Issue by ghosert** [ghosert/cmd-editor#1317]
点击在工具栏上的功能设置按钮或者快捷键 Ctrl+Alt+R，选择【自定义样式】菜单，在以下界面上书写自己的 CSS 样式，得到满意的效果后，回复本帖，提交 CSS，广受好评的样式有机会内置到今后的 Cmd Markdown 官方版本中。

![screenshot from 2016-05-15 17 28 25](https://cloud.githubusercontent.com/assets/236040/15273320/4af61f26-1ac7-11e6-9a20-29281e5a3c71.png)

如果您还不会书写 CSS 样式，可以[参考这里](https://zh.wikipedia.org/wiki/%E5%B1%82%E5%8F%A0%E6%A0%B7%E5%BC%8F%E8%A1%A8)学习，欢迎大家书写共享自己定义的 CSS 样式。

**Comment by zyl54586** [comment]
我就是来点赞的

**Comment by Little--ZM** [comment]
没啥审美等着大神的

**Comment by chenjuntong** [comment]
点赞。样式多了以后可以考虑转移到Wiki

**Comment by zzy0471** [comment]
# 抛砖引玉

我没有艺术细胞，但是看见大家都很羞涩，就先来抛砖引玉了。

## 代码

``` css
h1{
    font-size: 1.5em;
    color: #63B8FF;
}
h2{
    font-size: 1.3em;
    border-left:0.5em solid #9AC0CD;
    padding-left: 0.4em;
    background-color: #E5E5E5;
    padding:0.1em;
}
h3{
    font-size: 1.2em;
    border-bottom:1px solid #CCCCCC;
    padding-left: 0.4em;
    padding:0.1em;
}
```

## 效果

![Alt demo](http://static.zybuluo.com/zzy0471/gmfbmxo0sap7jw3vip771t8i/%E6%8D%95%E8%8E%B7.PNG)
