### ISSUE TITLE
标题标签中如果嵌入代码，代码的字体被限制在 14px，很不协调

### ISSUE THREAD

**Issue by catroll** [ghosert/cmd-editor#1339]
```
## 使用 `dd` 命令清空磁盘
```

CSS 设计不行，h2 中的 code 标签字体太小，丑。

``` css
.wmd-preview code, .wmd-preview pre {
    font-size: 14px;
}
```

**Comment by ghosert** [comment]
现在已经支持 CSS 了，可以自己自定义下。

**Comment by catroll** [comment]
额。。。
当然，我知道自己定义。
不过，感觉你们有问题都不想改啊～

**Comment by ghosert** [comment]
那你推荐一个合适的做法，随标题一起变大变小？和标题之间的大小比例是多少？

**Comment by catroll** [comment]
我自定义样式是这么写的：

``` css
h1 code, h2 code, h3 code, h4 code, h5 code, h6 code {
    font-size: inherit;
}
```

感觉就够用了吧。

当然，我不擅长前端，你们的前端工程师可能有更好的主意。。。
