### ISSUE TITLE
自定义的CSS样式在发布的HTML里不起作用

### ISSUE THREAD

**Issue by XieJiSS** [ghosert/cmd-editor#1905]
预览界面： ![preview](https://cloud.githubusercontent.com/assets/24671280/26407552/157c27b8-40ce-11e7-83fb-b2349ba9e0ea.png)，发布效果： ![image](https://cloud.githubusercontent.com/assets/24671280/26407652/51e2c28e-40ce-11e7-9912-baa64b0be0c4.png)

CSS:

```css
h1 {
    color: #0077bb; /* 将标题改为蓝色 */
}

code {
    font-size: 1.05em;
    color: #4e79b3;
    padding: 0 0.5em 0 0.5em;
}

a code {
    color: #ff7070;
}

a {
    text-decoration: underline;
}

a:hover, a:focus {
    text-decoration: none;
}
```

是特性如此吗？还是我的操作方式有问题？
