### ISSUE TITLE
Web端/mdeditor路径下用户批注图标(div.remark-icons)的z-index遮罩设置不正确

### ISSUE THREAD

**Issue by XieJiSS** [ghosert/cmd-editor#1907]
正确效果：
![image](https://cloud.githubusercontent.com/assets/24671280/26497635/c08e3010-425e-11e7-8c64-1bbab83cf829.png)

实际效果：
![image](https://cloud.githubusercontent.com/assets/24671280/26497556/82c1b248-425e-11e7-99e5-69f0cfd170fd.png)

patch:

```css
div.remark-icons {
    z-index: 49;
}
```

望改进，谢谢
