### ISSUE TITLE
<code> 标签中默认中文宋体的问题

### ISSUE THREAD

**Issue by PMExtra** [ghosert/cmd-editor#1919]
如题，发现code标签中的字体没有指定中文字体，建议修改默认CSS。

```css
code {
    font-family: Monaco,Menlo,Consolas,"Courier New",PingFang SC,Hiragino Sans GB,Helvetica Neue,Microsoft Yahei,WenQuanYi Micro Hei,sans-serif,monospace;
}
```
