### ISSUE TITLE
流程图不能完全显示

### ISSUE THREAD

**Issue by HelloMeow** [ghosert/cmd-editor#755]
![image](https://cloud.githubusercontent.com/assets/1561000/9296216/16ec6b74-44ba-11e5-90aa-73c423a5b761.png)

左侧预览会有一部分被遮挡无法显示，是否有显示区域大小的限制？

**Comment by zaiji100** [comment]
[https://www.zybuluo.com/zaiji100/note/162137](https://www.zybuluo.com/zaiji100/note/162137)

``` css
.sequence-diagram, .flow-diagram {
    text-align: center;
    margin: 0 auto;
    overflow: auto; //希望作者可以加上这一句，不然流程图看不了
}
```
