### ISSUE TITLE
流程图太大【宽】的话，超出的部分被屏蔽掉了

### ISSUE THREAD

**Issue by zaiji100** [ghosert/cmd-editor#927]
问题可以看这里: [https://zybuluo.com/zaiji100/note/162137](https://zybuluo.com/zaiji100/note/162137)
建议将 `*.layout.min.css` 中的

``` css
.sequence-diagram, .flow-diagram {
    text-align: center;
    margin: 0 auto;
}
```

改为

``` css
.sequence-diagram, .flow-diagram {
    text-align: center;
    margin: 0 auto;
    overflow: auto; /*增加了这一行，其他没变*/
}
```
